[testGUI.py:17 - accept_incoming_connections() ] Accepted an incoming connection from ('127.0.0.1', 50205)
